### ISSUE TITLE
post.thumbnail.src now producing garbage output after updating timber

### ISSUE THREAD

**Issue by glasswork** [jarednova/timber#540] opened 2015-05-15 17:48 UTC
I just updated from Version 0.20.5 to version 0.21.1 and instead of a lovely image, the following code:

`{{post.thumbnail.src | resize(600)}}`

now displays this:

![bad-juju](https://cloud.githubusercontent.com/assets/4681577/7658486/e86abc6c-faf7-11e4-9e56-efe0256e5fbd.jpg)

Any ideas?

**Comment by jarednova** [comment] 2015-05-16 19:46
@glasswork can you post some particulars of your situation. Here are some of the things that would be helpful: the image file and whatever `post.thumbnail.src` returns.

**Comment by glasswork** [comment] 2015-05-18 12:32
I did post what post.thumbnail.src returns ... it is the code seen in the screenshot below (and there are pages of it):
https://cloud.githubusercontent.com/assets/4681577/7658486/e86abc6c-faf7-11e4-9e56-efe0256e5fbd.jpg

The image it should have displayed (and previously did display) is:
http://ideum.com/wp-content/uploads/2014/10/blog-379-feature.png

**Comment by glasswork** [comment] 2015-05-27 16:39
This is still in needs-info ... what more do you need? I am happy to comply. But i will be unavailable for the two weeks following this one.

**Comment by glasswork** [comment] 2015-11-30 18:13
What more info do you need? I will gladly supply it to get a fix for this.

**Comment by connorjburton** [comment] 2016-03-11 20:04
Thanks for this info, this seems to be duplicate of #492 so I will close this, this issue will be fixed though.

**Closed by connorjburton** 2016-03-11 20:04 UTC
Labels: needs-info
