### ISSUE TITLE
Timber::get_widgets('sidebar'); always returns true

### ISSUE THREAD

**Issue by haluvibe** [jarednova/timber#511] opened 2015-03-31 08:54 UTC
In my single.php I have the following code

$context['sidebar'] = Timber::get_widgets('sidebar-right');

And in my base.twig I have:

                    {% if sidebar %}
                        <div class="col-xs-12 col-sm-4">
                            <aside class="layout-sidebar">
                                {{ sidebar }}
                            </aside>
                        </div>
                    {% endif %}

It always returns true even if there is no widgets in the sidebar-right.

This seems to function quite differently to dynamic_sidebar() which returns false if there is no content in the sidebar.

Am I doing something wrong or is this a feature not a bug?

**Comment by destefanis** [comment] 2015-05-21 22:08
I can't seem to find a solution to this issue, and since the sidebar isn't currently being used, it's rendering empty markup.

**Comment by oxyc** [comment] 2015-11-18 16:27
I use:
```twig
                {% if sidebar|trim %}
                    <div class="col-xs-12 col-sm-4">
                        <aside class="layout-sidebar">
                            {{ sidebar }}
                        </aside>
                    </div>
                {% endif %}
```

**Comment by connorjburton** [comment] 2016-02-25 12:31
Hi @haluvibe, is this still an issue for you?

**Comment by oxyc** [comment] 2016-02-25 14:09
Last I check back in november it was at least.

**Comment by connorjburton** [comment] 2016-02-25 14:12
Thanks @oxyc, will put it on my list to resolve

**Comment by connorjburton** [comment] 2016-02-25 14:46
Okay I've looked into this, according to the WP codex, Timber's implementation is correct, `Timber::get_widgets` is a wrapper around `dynamic_sidebar` which returns `true` if a sidebar **exists**, regardless of is it's active or not.

What you actually need to do (again according to the codex) is the following:

```php
if ( is_active_sidebar( 'sidebar-right' ) ) {
    $context['sidebar'] = Timber::get_widgets( 'sidebar-right' );
}
```

Then `{# if sidebar #} {# endif #}` will work as expected.

**Comment by oxyc** [comment] 2016-02-25 14:55
Yes, but the problem is when you're using a plugin which displays your widgets dynamically. The `is_active_sidebar()` call will evaluate to true while the widget isnt actually rendered. Instead a string with spaces (non-empty and therefore truthy) is returned.

What I personally suggest would be to simply trum the result of the sidebar contents and then an empty string would evaluate to `false`.

This is what I currently do: https://github.com/generoi/sage/blob/timber/lib/custom/preprocess.php#L43 and it works fine. Would just be a nice DX addition to have it trimmed already. At least it took me a while to figure out why it evaluated to true while there weren't actually any widgets.

**Comment by connorjburton** [comment] 2016-02-25 15:03
Hm okay thanks for the info, what plugin are you using? Is it fairly easily to replicate this behaviour?

**Comment by oxyc** [comment] 2016-02-25 15:11
I'm using [Display Widgets](https://wordpress.org/plugins/display-widgets/), but I assume the same result would come from [Dynamic Widgets](https://wordpress.org/plugins/dynamic-widgets/) too.

To replicate (sorry I'm not able to actually test this now, I'm just taking it from memory):

1. Create a sidebar area
2. Create a widget, assign it to the sidebar, and use the options to conditionally hide it on a certain page.

If you visit that page the, even if you use `is_active_sidebar()`, the returned value of `Timber::get_widgets( 'sidebar-right' )` will be a string of spaces, and thus evaluates to true. The problem is that the conditional in timber will most likely print out some HTML-elements that manipulate the grid.

---- 

For clarification I usually have several sidebar areas defined:
- Footer
- Header
- Right Sidebar
- etc..

Footer and header are usually static with the same widgets displayed on every page. The right sidebar is dynamic though. Instead of creating a `Right sidebar blog post` sidebar, and a `Right sidebar frontpage` sidebar. I opt for one single sidebar area where I dynamically hide/show widgets depending on the post type.

**Comment by oxyc** [comment] 2016-02-25 15:17
I guess my report is actually different from the initial report though. Your suggestion about wrapping the assignment with `is_active_sidebar()` should be enough in @haluvibe case. I still feel a simple `trim()` in favour of DX is worth it though.

**Closed** 2016-03-08 01:59 UTC
Labels: bug, has-patch
