### ISSUE TITLE
sprintf() internationalization problem

### ISSUE THREAD

**Issue by sparrox** [jarednova/timber#515] opened 2015-04-03 08:16 UTC
I generated a .po files with POEdit thanks to Timber's documentation and it's work well. But I have a problem with sprintf notation.

`{{__('%s', 'mytheme')|format(service.label)}}`
or
`<span title="{{__('%s', 'mytheme')|format(service.label)}}">`

When POEdit analyze files it doesn't replace the placeholder by the value label (I just have %s)

Is it a POEdit problem or it's due to Timber's sprintf notation ?

**Comment by jarednova** [comment] 2015-04-07 01:24
Hi @sparrox the problem is about the order in which the functions/filters execute, try this:
```twig
<span title="{{ __('%s' | format(service.label) , 'mytheme') }}">
```

**Comment by jarednova** [comment] 2015-04-07 01:32
@sparrox just added a handful of tests to [confirm the functionality](https://github.com/jarednova/timber/blob/master/tests/test-timber-twig.php#L33-L44)

**Comment by sparrox** [comment] 2015-04-08 09:04
I tried to change the order like you said but POEdit doesn't match the value (only '%s').

Did I missed something ?

**Comment by connorjburton** [comment] 2016-02-24 09:25
Hi @sparrox, is this still an issue for you?

**Comment by connorjburton** [comment] 2016-03-02 12:08
I am going to close this as I haven't had a reply. Feel free to comment at any point in time and I will re-open.

**Closed by connorjburton** 2016-03-02 12:08 UTC
Labels: needs-info

**Comment by langhenet** [comment] 2019-06-21 10:08
Hi @connorjburton , I'm having the same issue here. Poedit does not read that as a translatable string... should I open another issue?

**Comment by jarednova** [comment] 2019-07-01 03:26
@langhenet yes please. As you can see from the above, I tested this original issue pretty thoroughly. Please be as detailed as you can so I can re-create whatever error you encounter

**Comment by gchtr** [comment] 2019-07-01 06:33
@langhenet Did you use [PoEdit Pro](https://poedit.net/pro)? Because only with PoEdit Pro you get full Twig support out of the box.

**Comment by langhenet** [comment] 2019-07-01 06:40
@gchtr Yes I'm using poedit pro.

@jarednova Ok I'll open another issue
