### ISSUE TITLE
WP Query 

### ISSUE THREAD

**Issue by aa-navarro** [jarednova/timber#791] opened 2015-12-14 17:24 UTC
Hi!

Excited to learn something new. I've been searching all over the place for an example of how to apply wp_query with Timber, but no such luck.  

I need to build a page where two WP Queries are filtered to two different divs. These divs in turn are toggled with jQuery. The queries are filtered based on the post category. Can you provide a quick sketch of how I can do this with Timber?

**Comment by lmartins** [comment] 2015-12-14 20:29
Hi @aa-navarro,

If stick to Timber and invest some time to learning it I think you will love it and never want to do normal themes again. That is what happened to me.

You need in this case to make two queries, they are pretty much the same as doing a standard WP query, the only difference is that you will use `Timber::get_posts` method, something like:

```php
$args = array(
    'post_type'   => 'price-plan',
    'order'       => 'ASC',
    'orderby'     => 'menu_order',
    'tax_query' => array(
		array(
			'taxonomy' => 'plan_type',
			'field'    => 'slug',
			'terms'    => 'base-plan',
		),
	),
);

$data['price_plans'] = Timber::get_posts($args);
```

Here im querying a custom post type and using the standard parameters we could use in any WP query.
Im attaching the results to a pointer the `$data` array, which will then be passed into our template.

I would recommend go through the entire Wiki: https://github.com/jarednova/timber/wiki

**Comment by aa-navarro** [comment] 2015-12-14 21:36
Thank you so much, Luis!

**Comment by aa-navarro** [comment] 2015-12-17 19:37
Ok, here's what I'm trying to do: 

$data = Timber::get_context(); 
    
$args = Timber::get_posts(array(
  'post_type'      => 'article',
  'posts_per_page' => -1,
  'post_category'  => 'reviews',
  'orderby'        => ''
));
              
$data ['reviews'] = Timber::get_posts($args);

Timber::render('page-audience.twig', $data);$data = Timber::get_context(); 
    
$args = Timber::get_posts(array(
  'post_type'      => 'article',
  'posts_per_page' => -1,
  'post_category'  => 'reviews',
  'orderby'        => ''
));
              
$data ['reviews'] = Timber::get_posts($args);

Timber::render('page-audience.twig', $data);

But this doesn't render anything at all. Any help would be greatly appreciated!

**Comment by lmartins** [comment] 2015-12-17 20:25
Something's not right.
You should only call `$data = Timber::get_context();` once in that template file. That call gets a big object with multiple informations from the site. See https://github.com/jarednova/timber/wiki/Timber-docs#get_context

You mention on your first post that you were querying two post types and needed to render them in two divs.

One way to achieve that is by making those two queries and have them associated with two entries in the context. Something like:

```php
$args = array(
    'post_type'   => 'post_type_1',
    'posts_per_page' => -1,
);

$data['post_type_1'] = Timber::get_posts($args);

$args = array(
    'post_type'   => 'post_type_2',
    'posts_per_page' => -1,
);

$data['post_type_2'] = Timber::get_posts($args);
```
Replacing the `$args` and post names with what makes sense in your case. You should also check WordPress docs to see which params you can pass to the query. Timber accepts exactly the same params you would use in a regular WordPress query:
https://codex.wordpress.org/Class_Reference/WP_Query#Parameters

Hope that helps.

**Comment by aa-navarro** [comment] 2015-12-17 21:20
Hey Luis, 

Thanks for the input. Still struggling with this, but persevering. 
```
$data = array();

$data = Timber::get_context();

$args = array(
    'post_type'   => 'article',
    'post_category' => 'reviews',
    'posts_per_page' => -1,
);

$data = Timber::get_posts($args);

Timber::render('page-audience.twig', $data);
 ```

**Comment by alenabdula** [comment] 2015-12-19 13:27
```php
# Timber Context
$context = Timber::get_context();
# Add to context, for key "article"
$context['article'] = Timber::get_posts(
    array(
        'post_type'   => 'article',
        'post_category' => 'reviews',
        'posts_per_page' => -1,
    )
);
# Render view
Timber::render('page-audience.twig', $context );
```

Now in your template

```twig
{% for item in article %}
    {{ item.title }}
    <!-- do stuff here -->
{% endfor %}
```

Hope that helps.

**Comment by connorjburton** [comment] 2016-02-23 13:06
@alenabdula seems to have covered this so going to go ahead and close this.

**Closed by connorjburton** 2016-02-23 13:06 UTC

**Comment by Radascript** [comment] 2018-02-20 07:54
Hi everyone - I've been trying to solve a similar issue to @aa-navarro. I can't get my tax_query to work. Without the tax_query inside $args, everything works perfectly. Once I try to filter by tax_query, I get no posts. Here's the code:

```
<?php
// Disable all archive pages
if (is_archive()) {
    $wp_query->set_404();
    status_header(404);
    nocache_headers();
    include(__DIR__ . '/404.php');
    exit;
}

$context = Timber::get_context();
$context['page'] = new Timber\Post;

global $paged;
if (!isset($paged) || !$paged){
    $paged = 1;
}

 $args = [
        'posts_per_page' => 6,
        'paged' => $paged,
            'tax_query' => [
                [
                    'taxonomy' => 'countries',
                    'field'    => 'slug',
                    'terms'    => 'England',
                ]
            ],
];


$context['posts'] = new Timber\PostQuery($args, 'TimberPost');

Timber::render([
    "templates/page-england.twig",
], $context);

```

Please let me know if you have an idea how to fix the tax_query. Thank you.

**Comment by connorjburton** [comment] 2018-02-20 08:30
@Radascript are the taxonomies registered on posts or pages? I can see you are loading a page template but you are querying posts (because you haven't specified a `post_type`)

Also how are you registering the countries taxonomy

**Comment by Radascript** [comment] 2018-02-20 09:24
@connorjburton Hi Connor - thanks for the quick reply. Here's how I'm registering the taxonomy with a little custom plugin:

```
<?php
/*
Plugin Name: Custom Taxonomies for example.com
Description: Site specific taxonomies for example.com
*/

// Hook into the init action and call create_countries_taxonomy when it fires

add_action('init', 'create_countries_taxonomy', 0);

function create_countries_taxonomy() {

    // Labels part for the GUI

    $labels = [
        'name' => _x('Country', 'taxonomy general name'),
        'singular_name' => _x('Country', 'taxonomy singular name'),
        'search_items' =>  __('Search Countries'),
        'all_items' => __('All Countries'),
        'parent_item' => __('Parent Country'),
        'parent_item_colon' => __('Parent Initiative:'),
        'edit_item' => __('Edit Country'),
        'update_item' => __('Update Country'),
        'add_new_item' => __('Add New Country'),
        'new_item_name' => __('New Initiative Name'),
        'menu_name' => __('Countries'),
    ];

    // Now register the non-hierarchical taxonomy like tag

    register_taxonomy('topics', 'post', [
        'hierarchical' => true,
        'labels' => $labels,
        'show_ui' => true,
        'show_admin_column' => true,
        'query_var' => true,
        'rewrite' => ['slug' => 'country'],
    ]);
}

```

And then on the blog posts, I add / checkmark related terms.

**Comment by connorjburton** [comment] 2018-02-20 09:31
@Radascript Forgive me if I am missing something as I'm a bit rusty on WP, I haven't used PHP/Wordpress in a good 6 months or so.

I can't see where you are registering the taxonomy `countries`, I can see `topics` and maybe the rewrite (not sure if that actually allows you to query it) `country` but not `countries`, unless Wordpress pluralises the rewrite slug automatically? 

Another step to take, does your query work when just doing `wp_query` instead of Timber, easiest way to figure out if the issue is with Timber or your query

**Comment by Radascript** [comment] 2018-02-20 09:39
@connorjburton - oops, no you are right, the args 'taxonomy' value must match the registered slug. But mine does match that in my files. I changed my actual custom tax name (initiative) to 'country' for this question because I thought it would be simpler to follow. Ironically it made things more confusing.

Good idea on testing plain wp_query - will test it to see where the error lives.

**Comment by connorjburton** [comment] 2018-02-20 09:41
Haha no problem, if the wp query does work with your query then i'll have a quick look at Timber to see where it could be going wrong

**Comment by Radascript** [comment] 2018-02-20 10:02
@connorjburton thank you again for your help - you're right that the mistake was in the registration, the "topics" should have been the name of my taxonomy. Thanks!!

**Comment by noireagate** [comment] 2023-01-23 15:56
Hi everyone,
I hope someone would still answer me about this topic. I'm trying to convert in twig/timber a normal wpquery, cause i would like to show a slider with some date from the database, but this isn't working. This is my wp_query:
<div class="row ">             <?php
                // the query                
 $the_query = new WP_Query(array(
                    'posts_per_page'=>100,
                    'post_type'=> 'veicoli',
                    'post_status'=> 'publish',
                )); ?>                 
<?php if ( $the_query->have_posts() ) : while ( $the_query->have_posts() ) : $the_query->the_post(); ?>
<div class="col-md-3 col-sm-6 text-center mt-5">
<img  class="img-fluid" src="<?php echo get_the_post_thumbnail_url();?> " >
<h5 class=" align-middle text-dark mt-2"><a class="text-dark" href="<?php the_permalink(); ?>">
<?php the_title(); ?>
</a>
</h5>
</div>                 
<?php endwhile; else: ?><p><?php _e('Nessun articolo corrisponde ai criteri di ricerca.'); ?></p>
<?php endif; ?>
</div>
How can I convert this to be readable for a twig file? I've searched and seems that there is no way to write directly this php code in a twig site. Maybe @connorjburton  could you help me?  Thank you so much in advance.

**Comment by noireagate** [comment] 2023-01-23 15:56
i'll rewrite the wp_query since seems to be cut:
<div class="row ">             <?php
                // the query                
 $the_query = new WP_Query(array(
                    'posts_per_page'=>100,
                    'post_type'=> 'veicoli',
                    'post_status'=> 'publish',
                )); ?>                 
<?php if ( $the_query->have_posts() ) : while ( $the_query->have_posts() ) : $the_query->the_post(); ?>
<div class="col-md-3 col-sm-6 text-center mt-5">
<img  class="img-fluid" src="<?php echo get_the_post_thumbnail_url();?> " >
<h5 class=" align-middle text-dark mt-2"><a class="text-dark" href="<?php the_permalink(); ?>">
<?php the_title(); ?>
</a>
</h5>
</div>                 
<?php endwhile; else: ?><p><?php _e('Nessun articolo corrisponde ai criteri di ricerca.'); ?></p>
<?php endif; ?>
</div>

**Comment by noireagate** [comment] 2023-01-23 15:57
i'll rewrite the wp_query since seems to be cut: `<div class="row ">             <?php
                // the query                
 $the_query = new WP_Query(array(
                    'posts_per_page'=>100,
                    'post_type'=> 'veicoli',
                    'post_status'=> 'publish',
                )); ?>                 
<?php if ( $the_query->have_posts() ) : while ( $the_query->have_posts() ) : $the_query->the_post(); ?>
<div class="col-md-3 col-sm-6 text-center mt-5">
<img  class="img-fluid" src="<?php echo get_the_post_thumbnail_url();?> " >
<h5 class=" align-middle text-dark mt-2"><a class="text-dark" href="<?php the_permalink(); ?>">
<?php the_title(); ?>
</a>
</h5>
</div>                 
<?php endwhile; else: ?><p><?php _e('Nessun articolo corrisponde ai criteri di ricerca.'); ?></p>
<?php endif; ?>
</div>`

**Comment by noireagate** [comment] 2023-01-23 15:59
ok, i don't know why my wp_query has been cut, anyway this is my code:
![image](https://user-images.githubusercontent.com/108992823/214086568-aeb74732-bc91-4697-8858-6f7787d76162.png)
I'm sorry i'm new to github and twig/timber
