### ISSUE TITLE
Caching Issues

### ISSUE THREAD

**Issue by taytorious** [jarednova/timber#289] opened 2014-07-10 15:25 UTC
I recently had an issue where one of my templates wasn't grabbing a custom field value. The field was the text for a submit button, and the text didn't show even when the text was hard coded into the template. I began to make many other changes to the template just to test, and none of them were reflected in the end result. I ended up making a new template, naming it something else, and now it is working fine. It is my understanding that all fields are hashed in the view context and the cache is invalidated as soon as the data changes. Is there any reason why this wouldn't happen? Is there anything I can do to prevent it from happening in the future? Below is a screenshot:
![screen_shot_2014-05-16_at_10 15 44_am](https://cloud.githubusercontent.com/assets/6719714/3540746/d6473920-0845-11e4-9f12-eb191648c102.png)

And the code:

{% extends "action.twig" %}

{% block action_body %}

    <div class="take-action__a">
        <p>{{ post.call_to_action.description }}</p>
        <small>{{ take_action_privacy_policy_text }}</small>
    </div>

    <div class="take-action__b">
        <form id="support-action-form" class="cf">
            <div class="form-element">
                <label for="ta-first-name">First Name</label>
                <input name="first_name" type="text" id="ta-first-name" class="text-input text-input--thin" required>
            </div>

            <div class="form-element">
                <label for="ta-last-name">Last Name</label>
                <input name="last_name" type="text" id="ta-last-name" class="text-input text-input--thin" required>
            </div>

            <div class="form-element">
                <label for="ta-email">Email</label>
                <input name="email" type="email" id="ta-email" class="text-input text-input--thin" required>
            </div>

            <div class="form-element">
                <label for="ta-message">Message</label>
                <textarea cols="40" rows="5" name="message" id="ta-message" class="text-area" required></textarea>
            </div>

            <div class="form-element">
                <input type="hidden" name="ssname" value="{{ post.call_to_action.spreadsheet_name }}">
                <input type="hidden" name="wsname" value="{{ post.call_to_action.worksheet_name }}">
            </div>

            <button type="submit" class="btn btn--solid btn--external icon icon_external">{{ post.call_to_action.submit_button_text }}</button>
        </form>
    </div>
{% endblock %}

Our hosting provider is wpengine if that makes a difference. Thanks for the help!

**Comment by mgmartel** [comment] 2015-02-18 04:04
Hi @taytorious,

I have been trying to figure what's going on here, but didn't find anything. I did see on your site ([here](http://nationswell.com/dont-like-citys-bus-service-guy-built/?cta=show) right?) that the label is now showing correctly. Does this mean the problem is fixed? If so.. what was it??

Mike

**Comment by connorjburton** [comment] 2016-02-24 10:57
As there hasn't been any activity on the issue i'm going to assume it's been solved and close this. Feel free to comment if this is still an issue.

**Closed by connorjburton** 2016-02-24 10:57 UTC

**Comment by pjoulot** [comment] 2022-02-18 09:00
Interesting, I have the same issue. My website is behaving the same way on my local and digital ocean, but on wp engine it becomes crazy...
